server.port=9191
eureka.instance.client.serverUrl.defaultZone=http://localhost:8761/eureka 

eureka.client.refresh.enable=false

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
spring.cloud.gateway.server.webmvc.routes[0].id=book-service
spring.cloud.gateway.server.webmvc.routes[0].uri=lb://book-service
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/api/v1/book-controller/**

spring.cloud.gateway.server.webmvc.routes[1].id=AuthService
spring.cloud.gateway.server.webmvc.routes[1].uri=lb://AuthService
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/login,/signup,/init,/message,/save-more-details,/profile

spring.cloud.gateway.server.webmvc.routes[2].id=order-service
spring.cloud.gateway.server.webmvc.routes[2].uri=lb://order-service
spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/api/v1/order-controller/**,/api/v1/notification-controller/**



management.tracing.export.enabled=true
management.tracing.sampling.probability=1.0


management.tracing.export.zipkin.endpoint=http://localhost:9492/api/v2/spans
